# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NUX Institute
longname: Natural User Experience Institute
tagline: Researching what makes intuitive interactions <i>natural</i>.
email: g.moorhouse@me.com
description: >-
  The NUX Institute was founded in 2023 at Politecnico di Milano with the goal of investigating what makes interactions and user experiences natural.
baseurl: ""
url: "https://nux.institute"
domain: nux.institute

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Algolia Search
  
algolia:
  index_name: dev_nuxi
  application_id: QM4XV03JPH
  search_only_api_key: e2dc28b4494e34cb1ba8c22c4a60f401

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
